const fs = require('fs');
let t = fs.readFileSync('server/src/routes/template.routes.ts', 'utf8');
const lines = t.split('\n');
const n = [];
n.push("        let doc: any;");
n.push("        {");
n.push("            console.log('[DOCX] Direct XML replace (preserves tables)');");
n.push("            const xmlFiles = ['word/document.xml'];");
n.push("            for (const fn of Object.keys(zip.files)) {");
n.push("                if (/^word\\\\/(header|footer)\\\\d*\\\\.xml$/i.test(fn)) xmlFiles.push(fn);");
n.push("            }");
n.push("            for (const xf of xmlFiles) {");
n.push("                let x = zip.file(xf)?.asText();");
n.push("                if (!x) continue;");
n.push("                x = x.replace(/(<w:t[^>]*>)([^<]*)<\\/w:t>/g, (_m: string, tag: string, txt: string) => {");
n.push("                    let r = txt;");
n.push("                    for (const [k, v] of Object.entries(vars)) {");
n.push("                        if (typeof v === 'string') r = r.split('{{' + k + '}}').join(v as string);");
n.push("                    }");
n.push("                    return tag + r + '</w:t>';");
n.push("                });");
n.push("                zip.file(xf, x);");
n.push("            }");
n.push("            doc = { getZip: () => zip, getFullText: () => '', render: () => {} };");
n.push("        }");
lines.splice(391, 15, ...n);
fs.writeFileSync('server/src/routes/template.routes.ts', lines.join('\n'));
console.log('Done:', n.length, 'lines');